feat: added cypress tests and ci (#14)
* test: cypress setup and dropdown test

* test: cypress testing branch

* fix: update cypress version

remove error:
```
TSError: ⨯ Unable to compile TypeScript:
error TS5095: Option 'bundler' can only be used when 'module' is set to 'es2015' or later.
```

* fix: rebuild pnpm.lock

* chore: updated dependencies

* ci: updated ci to include cypress tests

* ci: fix for prettier step in lint job

---------

Co-authored-by: Pratik Borole <borolepratik@gmail.com>